collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.2959183
  brandStrength: 0.2748161
  lightness: 0.7663802
  brandColors:
    - '#A78C6F'
    - '#0192EA'
    - '#001723'
    - '#3F6801'
    - '#FFF8FF'
  rhythmicContrast: 0.2003222
typography_spectrum: 0.2669173
layout_spectrum: 1
name: Saxphoto
